function MsubjectTime=combine_loose_strict(MsubjectTime)


MsubjectTime.CombinedSepiLineages=CombineLooseStrict(MsubjectTime.sepi_clusterlev_concatenated_conservative,MsubjectTime.sepi_clusterlev_concatenated_loose,MsubjectTime);
MsubjectTime.CombinedSepiSubphylo=CombineLooseStrict(MsubjectTime.sepi_subphylolev_concatenated_conservative,MsubjectTime.sepi_subphylolev_concatenated_loose,MsubjectTime);
MsubjectTime.CombinedSepiPhylo=CombineLooseStrict(MsubjectTime.sepi_phylolev_concatenated_conservative,MsubjectTime.sepi_phylolev_concatenated_loose,MsubjectTime);
MsubjectTime.CombinedCacnesLineages=CombineLooseStrict(MsubjectTime.cacnes_clusterlev_concatenated_conservative,MsubjectTime.cacnes_clusterlev_concatenated_loose,MsubjectTime);
MsubjectTime.CombinedCacnesPhylotypes=CombineLooseStrict(MsubjectTime.cacnes_phylolev_concatenated_conservative,MsubjectTime.cacnes_phylolev_concatenated_loose,MsubjectTime);