%%  Highly-resolved within-species dynamics in the human facial skin microbiome
%   This script reproduces the data presented in Baker et al. 2024


%% required paths 


workingdir=pwd;
path(pwd,path);

% for UMAP
path('./umap',path);
path('./epp',path);

% for making colormaps
path('./cbrewer2',path);

% points to BLASTn executable
setenv('PATH','/Users/jakebaker/miniconda3/bin:/Users/jakebaker/miniconda3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin')


%% load colormaps 


% Color blindness friendly color scheme used in figures.
ManuscriptColors = load_manuscript_colors;


%% Locations of required pre-generated data structures.


%   TYPE is either metagenomics_tubes or isolates
%   data/bracken/{metagenomics_tubes or isolates}/{SAMPLENAMES}.G.bracken, genus-level bracken data
%   data/bracken/{metagenomics_tubes or isolates}/{SAMPLENAMES}.S.bracken, species-level bracken
%   note that the files are run with human reads, which are removed before
%   uploading to public repository as per IRB protocol
    bracken_dir='data/bracken';

% Candidate mutation tables for all samples aligned to two references
%   244 preliminary metagenomics samples are included here as well but are
%   ignored, and these structures are used only for isolate-wise analyses
%   data/SepidermidisATCC12228_candidate_mutation_table.mat
%   data/Pacnes_C1_candidate_mutation_table.mat
    cacnes_reference_mapping='Pacnes_C';
    sepi_reference_mapping='SepidermidisATCC12228';
    candidate_mutation_table_cacnes='data/Pacnes_C1_candidate_mutation_table.mat';
    candidate_mutation_table_sepi='data/SepidermidisATCC12228_candidate_mutation_table.mat';

% Genome assemblies
% data/Assembly/isolate_assemblies/
%   sumStats_assembly_annotation.tsv contains information for each unfiltered assembly
    AssemblyStats   = readtable('data/Assembly/isolate_assemblies/sumStats_assembly_annotation.tsv','FileType','text','Delimiter',{' ','\t'},'ReadVariableNames',1);
%   assemblies/{samplename}/contigs.fasta contains all raw assemblies for
%   each isolate
%   annotations/{samplename}/prokka_out.faa contains prokka annotation for
%   each isolate
%   CDHIT_used_for_filtering_isolates/cdhit_results.clstr is 90% similarity CDHIT of prokkas
%   prokka files were re-labeled with a bash script to add samplename to
%   each fasta row entry 
    cdhit_isolate_assemblies_90percent='data/Assembly/isolate_assemblies/CDHIT_used_for_filtering_isolates/cdhit_results.clstr';

% metadata tables
    ncbi_references = readtable('ncbi_reference_genomes.csv');
    SampleNames = readtable('samplenames.csv','NumHeaderLines',0);

% commands used to move tables to supplemental table folder
! cp  ncbi_reference_genomes.csv data/SupplementaryTables/ST6_reference_genomes.csv
! cp data/Assembly/isolate_assemblies/sumStats_assembly_annotation.tsv data/SupplementaryTables/assembled_isolate_genomes_raw.tsv;


%% cluster-computed data structures used between modules of this script


%   resized version of data/{species}_candidate_mutation_table.mat to prevent slow re-computing
%   of counts matrix, major allele frequency:
%   data/{species}_UnfilteredMutationVars.mat generated by resize_candidate_mutation_table.m
    CacnesUnfilteredMutationsFile='data/Pacnes_C1_UnfilteredMutationVars.mat';
    SepiUnfilteredMutationsFile='data/SepidermidisATCC12228_UnfilteredMutationVars.mat';
%   data/DMinputs.mat % generated by get_DMinputs.m, takes UnfilteredMutationVars.mat and boolean (GoodSepiBool/GoodCacnesBool)
    DMinputsFile='data/DMinputs.mat';
%   dm_generation_cloned_from_cluster.dm/get_distance_matrices_GPU.m:
%   data/DMs.mat % takes DMinputs
    DMsFile='data/DMs.mat';


%% Metagenomics sample filtering 


% Load unfiltered tube-wise metagenomics data from raw data files
% identify tubes which are picking up contamination from handlers
% exclude tubes, then get indices for concatenated samples (subject 1,
% subject 1 tp1, subject 1 tp2, et cetera)
%re-load good tubes with newest instance of PHLAME data, a different
%version than what was used in the initual filtering. 

% loads tube-wise data for filtrering based on sampling subjects and old methods
M_tubes_all = fill_metagenomics_info; 

% filter out samples with contamination
[Mfilt] = filter_table(M_tubes_all); %this version didnt spit out data for control subjects, I fixed it to add these rows since they are what is saved.

IndicesForConcatenatedTubes = get_indices_concatenated_reads(Mfilt);
% writes indices for samples to be concatenated together 
writetable(IndicesForConcatenatedTubes,'data/IndicesForConcatenatedReadAnalysis_31JUl23.csv','Delimiter',',')


%% Load concatenated metagenomics (from idices above) 


% Get indices of tubes used to concatenated together
T=readtable('data/IndicesForConcatenatedReadAnalysis_31JUl23.csv');

n = T.IndicesONEIndexed;
n = string(n);
n= arrayfun(@(x) {strsplit(x,' ')}, n);
n= cellfun(@(x) {str2double(x)}, n);
idx_good_tubes=unique(horzcat(n{:}));

%  now that you have good indice,s use trhem for the more refined analysis in fill_metagenomics_filtered.
% need to fix. tubewise data only goes to 603, not 604
% tubes arent even used for anythign right now anyways
M_all = fill_metagenomics_info_filtered;
M_all = M_all(ismember(M_all.index,idx_good_tubes),:);
% M_all at this point should have 546 rows

% should unify this data structure with the more useful ConcatenatedReadData which comes later
% I noticed that some samples have high C. acnes coverage but low assignment. this is a bug in the code for fill_metagenomics_info_filtered, for example, 7PB
% this should only matter for concatenated kits.
% I correct it manually below
% this part adds corrected concatenated data to each
% M = add_correct_concatenated_kits(M)
% Needs to be absorved into above. 
M_all_filtered = filter_table_to_families(M_all); % when run with M_all, is correct size (463)

% Average and normalize relavent data to get subject/time point and
% subject-wise data
ConcatenatedReadData = get_ConcatenatedReadsPHLAMEData;
[Msubject, MsubjectTime, Mtubes]=parse_metagenomics_tubes(M_all_filtered,ConcatenatedReadData);


%% Parse CDHIT data of each C. acnes and S. epi isolate assembly annotation, in addition to reference genomes from NCBI


% parse CDHIT data structure
% CDHITData=parse_cdhit_isolates(CDHIT output file,samplenames of isolates we have assembles ,names of reference genomes);
CDHITData=parse_cdhit_isolates(cdhit_isolate_assemblies_90percent,AssemblyStats,ncbi_references);


%% Write table of homologues x samples to supplementary tables
% too big to save in square form, will not open in excel. 


[C,S]=size(Array);

idx_row =((1:C)').*CDHITData.CDHITClusterxSamples;
SampleNamesArray   = repmat(CDHITData.SampleNames,C,1);

% expand to 1D
homologue_number =(idx_row(:));
SampleNamesArray=(SampleNamesArray(:));

% remove 0 rows to save space
keep=homologue_number>0;
SampleNamesArray=SampleNamesArray(keep);
homologue_number=homologue_number(keep);

% make space delimited list
clusters_each_sample=arrayfun(@(x) {unique(homologue_number(SampleNamesArray==x))},CDHITData.SampleNames);
clusters_each_sample=arrayfun(@(x) {strjoin(string(x{:}),' ')}, clusters_each_sample);
clusters_each_sample=vertcat(clusters_each_sample{:});

% make table
CDHITHomologuesTableSupplement = table;
CDHITHomologuesTableSupplement.SampleNames = CDHITData.SampleNames;
CDHITHomologuesTableSupplement.clusters_each_sample = clusters_each_sample;

% save
writetable(CDHITHomologuesTableSupplement,'data/SupplementaryTables/CDHIT_homologues_isolates.csv')


%% filter isolates based on their core genome content


% outputs are size 1x7443 with the first 7199 entries corrosponding to samples in SampleNames.SampleName
% in order to be compatable with candidate_mutation_table.mat, which was
% run with 7443 samples (last 244 corrospond to metagenomics pilot samples)
[GoodStaphisolate, GoodCacnesIsolate] =  core_genome_filter(CDHITData,AssemblyStats,ncbi_references,SampleNames.SampleName);


%% Resize candidate_mutation_table if it is too large to open locally


% this function is meant to be run on a cluster with lots of RAM but can be
% run locally if necessary
% was originally meant to prevent re-computing of maF, maNT, coverage, et
% cetera
CacnesUnfilteredMutationVars = resize_candidate_mutation_table(candidate_mutation_table_cacnes,cacnes_reference_mapping);
SepiUnfilteredMutationVars = resize_candidate_mutation_table(candidate_mutation_table_sepi,sepi_reference_mapping);


%% on cluster: get inputs for generating distance matrices on cluster using GPUs


% cutoffs such as min major allele frequency are hard coded
% assumes UnfilteredMutationVars is precomputed
DMinputs = get_DMinputs;
save('DMinputs.mat','DMinputs','-V7.3')

%% Generate distance matrices for clustering isolates into lineages
% This step was run on Slurm based HPC
% see scripts/distance_matrix for details

get_distance_matrices_GPU.m


%% this regenerates clusters of lineages for both species
% This step was run on Slurm based HPC
% see scripts/clustering for details

run_clustering


%% identity de novo mutations in lineage 


%CSV used on cluster to align samples to clade co-assemblies
SamplesCSV = readtable('cluster_assemblies_with_outgroup_no_singletons_no_doubletons.csv');
clade_names = string(unique(SamplesCSV.ReferenceGenome));

% create parameters structure
params = struct;
% % For filtering individual calls
params.min_qual_for_call = 30;
params.min_maf_for_call = .75;
params.min_cov_for_call = 4;

% For filtering positions
params.max_fraction_ambigious_samples = .4;

% to filter maNT for anlysis 
params.min_maf_for_analysis = .7;
params.min_coverage_for_analysis = 5; % for each call (fwd+rev)

% Promoter mutations: how far upstream of the nearest gene to annotate something a promoter mutation
params.promotersize = 150;
params.NTs = 'ATCG';    
% location of asssemblies for each clade with filtered contigs
params.REFGENOMEDIRassemblies = [pwd '/data/Assembly/clade_coassemblies/clades_filtered_contigs'];
% where to put subject-seperated phylogenies
params.SubjectLineageTrees=[pwd '/data/subject_lineage_phylogenies'];
% directory in which to place S. epi assembly trees
CLUSTERSDIRsepi='sepi_assembly_trees';
CLUSTERSDIRcacnes='cacnes_assembly_trees';

% % identify de novo mutations  in Sepi, build trees, get data for other thing
[SepiLineages]= identify_mutations_lineage_assemblies(CLUSTERSDIRsepi,clade_names(contains(clade_names,"sepi")), params);

% identify de novo mutations  in Cacnes, build trees, get data for other thing
CacnesLineages = identify_mutations_lineage_assemblies(CLUSTERSDIRcacnes,clade_names(contains(clade_names,"cacnes")), params);

% get lineage data and put it all into a single structure
SepiLineages = struct2table(SepiLineages);SepiLineages.SpeciesName = repmat("sepi",numel(SepiLineages.cladenumber),1);
CacnesLineages = struct2table(CacnesLineages);CacnesLineages.SpeciesName = repmat("cacnes",numel(CacnesLineages.cladenumber),1);
LineageData = [CacnesLineages ;    SepiLineages ];

% get annotations for both species
sepi_annotations_all = horzcat(LineageData.annotations{LineageData.SpeciesName=="sepi"});
cacnes_annotations_all=horzcat(LineageData.annotations{LineageData.SpeciesName=="cacnes"});

% save data
save('data/annotations_all.mat','cacnes_annotations_all','sepi_annotations_all')
save('data/LineageData','LineageData')


%% Write annotations to supplementary table but remove things hard to parse in csv format


sepi_annotations_all_table = annotations2supplement(sepi_annotations_all);
cacnes_annotations_all_table = annotations2supplement(cacnes_annotations_all);

% write to supplement
writetable(sepi_annotations_all_table,'data/SupplementaryTables/sepi_annotations_all.csv')
writetable(cacnes_annotations_all_table,'data/SupplementaryTables/cacnes_annotations_all.csv')


%% Cluster subjects based on species-metagenomics abundances


% Runs UMAP to cluster subject timepoint sammples.
% Fig. 2A,Fig. 2B,Fig. 2D,Fig. 2E
% Fig. SXX
% adds cutotypes to MsubjectTime
MsubjectTime=umap_facial_cutotypes(MsubjectTime,ManuscriptColors);

% Fig. 2C
f=alpha_diversity_subject(Msubject.subject_cutotype,vertcat(Msubject.BrackenSpecies{:}),ManuscriptColors.CutotypeColors); % each dot it a subject, used concatenated data from umap projection
saveas(f,'ManuscriptFigures/AlphaDiversitySpeciesLevelBySubject.svg','svg')


%% Add cutotype information to Mtubes and Msubects 


% By subject 
uSubjects = Msubject.SID;
SubjectsSubjectTime=MsubjectTime.SID;
subject_cutotype=arrayfun(@(x) max(clusters_umap_subjecttime_bracken_species(x==SubjectsSubjectTime)), uSubjects);
subject_cutotype(Msubject.Age>18)=3;

% individual tubes
Mtubes.subject_cutotype=arrayfun(@(x) subject_cutotype(x==uSubjects), Mtubes.SID);
MsubjectTime.subject_cutotype=arrayfun(@(x) subject_cutotype(x==uSubjects), MsubjectTime.SID);
Msubject.subject_cutotype=subject_cutotype;


%% removes low-quality lineages from metagenomics data, including lineages found in mock communities


[IT,LineageData] = LineageDataToTable(LineageData);
[Msubject,MsubjectTime,Mtubes]=exclude_lineages(IT,Msubject,MsubjectTime,Mtubes);
writetable(IT,'data/SupplementaryTables/isolates.csv')


%% adds combined metagenomics data to subject timepoint data


MsubjectTime.CombinedSepiLineages=CombineLooseStrict(MsubjectTime.sepi_clusterlev_concatenated_conservative,MsubjectTime.sepi_clusterlev_concatenated_loose,MsubjectTime);
MsubjectTime.CombinedSepiSubphylo=CombineLooseStrict(MsubjectTime.sepi_subphylolev_concatenated_conservative,MsubjectTime.sepi_subphylolev_concatenated_loose,MsubjectTime);
MsubjectTime.CombinedSepiPhylo=CombineLooseStrict(MsubjectTime.sepi_phylolev_concatenated_conservative,MsubjectTime.sepi_phylolev_concatenated_loose,MsubjectTime);
MsubjectTime.CombinedCacnesLineages=CombineLooseStrict(MsubjectTime.cacnes_clusterlev_concatenated_conservative,MsubjectTime.cacnes_clusterlev_concatenated_loose,MsubjectTime);
MsubjectTime.CombinedCacnesPhylotypes=CombineLooseStrict(MsubjectTime.cacnes_phylolev_concatenated_conservative,MsubjectTime.cacnes_phylolev_concatenated_loose,MsubjectTime);
% writetable 

%% Filter subject/time point isolate data based on the number of isolates


% minimum clustered isolates to include subject/timepoint
min_iso=25;
[IsolateArrays] = IsolateTimepointAbundances(IT,MsubjectTime);

% normalize abundances
AsepiIso=IsolateArrays.SepiIsolates;
AcacnesIso=IsolateArrays.CacnesIsolates;
TotalSepi = sum(AsepiIso,2);
TotalCacnes=sum(AcacnesIso,2);
AsepiIso(TotalSepi<min_iso,:)=0;
AcacnesIso(TotalCacnes<min_iso,:)=0;
AsepiIso=AsepiIso./sum(AsepiIso,2);
AcacnesIso=AcacnesIso./sum(AcacnesIso,2);
AsepiIso(isnan(AsepiIso))=0;
AcacnesIso(isnan(AcacnesIso))=0;


%% Bray curtist of self-over-time composition for each combined metagenomics dataset above


% Supplementary Figure XX
p=figure; hold on
MinAssigned=0.70;
cutoff_real=0.0;
subplot(2,4,1)
IsoCacnesLineages = BrayCurtisOverTime_twostep(AcacnesIso,IsolateArrays,MinAssigned,.01,"C. acnes lineages, Isolates");
subplot(2,4,2)
MGCacnesLineages = BrayCurtisOverTime_twostep(MsubjectTime.CombinedCacnesLineages,MsubjectTime,MinAssigned,cutoff_real,"C. acnes lineages, Metagenomics");
subplot(2,4,3)
MGCacnesPhylo = BrayCurtisOverTime_twostep(MsubjectTime.CombinedCacnesPhylotypes,MsubjectTime,MinAssigned,cutoff_real,"C. acnes phylotypes, Metagenomics");
subplot(2,4,5)
IsoSepiLineages = BrayCurtisOverTime_twostep(AsepiIso,IsolateArrays,MinAssigned,cutoff_real,"S. epidermidis lineages, Isolates");
subplot(2,4,6)
MGSepiLineages = BrayCurtisOverTime_twostep(MsubjectTime.CombinedSepiLineages,MsubjectTime,MinAssigned,cutoff_real,"S. epidermidis lineages, Metagenomics");
subplot(2,4,7)
MGSepiSubphylo = BrayCurtisOverTime_twostep(MsubjectTime.CombinedSepiSubphylo,MsubjectTime,MinAssigned,cutoff_real,"S. epidermidis subphylotypes, Metagenomics");
subplot(2,4,8)
MGSepiPhylo = BrayCurtisOverTime_twostep(MsubjectTime.CombinedSepiPhylo,MsubjectTime,MinAssigned,cutoff_real,"S. epidermidis phylotypes, Metagenomics");

saveas(p,'ManuscriptFigures/BrayCurtisOverTimeTwostep.svg')


%% for main text, take S. epi and C. acnes lineage level ones from metagenomics

% Figure 4C
p=figure
hold on
[~] = BrayCurtisOverTime_twostep(MsubjectTime.CombinedCacnesLineages,MsubjectTime,MinAssigned,cutoff_real,"C. acnes lineages, Metagenomics");
[~] = BrayCurtisOverTime_twostep(MsubjectTime.CombinedSepiLineages,MsubjectTime,MinAssigned,cutoff_real,"S. epidermidis lineages, Metagenomics");

Cacnes = cellfun(@(x) max(x),MGCacnesLineages.BetaDissimilarityFromInitial)
Sepi = cellfun(@(x) max(x),MGSepiLineages.BetaDissimilarityFromInitial)

[h,pval,k]=kstest2(Sepi,Cacnes)

saveas(p,'ManuscriptFigures/BrayCurtisOverTimeTwostep_sepi_cacnes_lineages_singleplot_p0164.svg')


%% plot and compare change over time for lineage level intervals


% Figure 4A
% Figure 4B
p=compare_2_dynamics(MGCacnesLineages,MGSepiLineages,"PHLAME lineages")
saveas(p,'ManuscriptFigures/AbundanceLostMGLineages.svg')


%% average number of C. acnes lineages per subject which are not found on related family members


% Supplementary Figure XX
CombinedLineages=MsubjectTime.CombinedCacnesLineages;

MsubjectTime_filt=MsubjectTime(sum(CombinedLineages,2)>MinAssigned,:);
CombinedLineages_filt=CombinedLineages(sum(CombinedLineages,2)>MinAssigned,:);
FamilyNumbers = get_family_numbers(MsubjectTime_filt.SID);
bool=arrayfun(@(x) sum(FamilyNumbers==x)>1, FamilyNumbers);
MsubjectTime_filt=MsubjectTime_filt(bool,:);
CombinedLineages_filt=CombinedLineages_filt(bool,:);

UniqueSubjects = unique(MsubjectTime_filt.SID);

AllEverFound_Lineages = arrayfun(@(x) {sum(CombinedLineages_filt(x==MsubjectTime_filt.SID,:),1)}, UniqueSubjects);
FamilyNumbers = get_family_numbers(UniqueSubjects);
AllEverFound_Lineages=vertcat(AllEverFound_Lineages{:});
unique_lineages=arrayfun(@(x) sum(AllEverFound_Lineages(x,sum(AllEverFound_Lineages( (FamilyNumbers(x)==FamilyNumbers&(1:numel(FamilyNumbers)~=x)),:),1)==0)>0), 1:numel(FamilyNumbers));

f=figure;
idx = arrayfun(@(x) find(x==Msubject.SID), UniqueSubjects);
MsubjectPlot = Msubject(idx,:);
swarmchart(MsubjectPlot.subject_cutotype,unique_lineages,'filled','CData',ManuscriptColors.CutotypeColors(MsubjectPlot.subject_cutotype,:))
xlim([0 4])
xticks(1:3)
xticklabels(["FC1-Children" "FC2-Children" "Parents"])
saveas(f,'ManuscriptFigures/CacnesNumberLineagesNeverFoundFamily.svg')


%% average number of S. epidermidis lineages per subject which are not found on related family members


% Supplementary Figure XX
CombinedLineages=MsubjectTime.CombinedSepiLineages;

MsubjectTime_filt=MsubjectTime(sum(CombinedLineages,2)>MinAssigned,:);
CombinedLineages_filt=CombinedLineages(sum(CombinedLineages,2)>MinAssigned,:);
FamilyNumbers = get_family_numbers(MsubjectTime_filt.SID);
bool=arrayfun(@(x) sum(FamilyNumbers==x)>1, FamilyNumbers);
MsubjectTime_filt=MsubjectTime_filt(bool,:);
CombinedLineages_filt=CombinedLineages_filt(bool,:);
f=figure;
UniqueSubjects = unique(MsubjectTime_filt.SID);

AllEverFound_Lineages = arrayfun(@(x) {sum(CombinedLineages_filt(x==MsubjectTime_filt.SID,:),1)}, UniqueSubjects);
FamilyNumbers = get_family_numbers(UniqueSubjects);
AllEverFound_Lineages=vertcat(AllEverFound_Lineages{:});
unique_lineages=arrayfun(@(x) sum(AllEverFound_Lineages(x,sum(AllEverFound_Lineages( (FamilyNumbers(x)==FamilyNumbers&(1:numel(FamilyNumbers)~=x)),:),1)==0)>0), 1:numel(FamilyNumbers));

idx = arrayfun(@(x) find(x==Msubject.SID), UniqueSubjects);
MsubjectPlot = Msubject(idx,:);
swarmchart(MsubjectPlot.subject_cutotype,unique_lineages,'filled','CData',ManuscriptColors.CutotypeColors(MsubjectPlot.subject_cutotype,:))
xlim([0 4])
xticks(1:3)
xticklabels(["FC1-Children" "FC2-Children" "Parents"])
saveas(f,'ManuscriptFigures/SepiNumberLineagesNeverFoundFamily.svg')


%% Abundance of C. acnes and S. epi together in microbiome


A = vertcat(Msubject.BrackenSpecies{:});
A=A(contains(Msubject.SID,"P"),:);
Names=Msubject.NamesSpecies(1,:);
A=A(:,Names=="Cutibacterium acnes"|Names=="Staphylococcus epidermidis");
A=sum(A,2);

mean(A)


%% plot the clade-level dynamics on all subjects with at least 3 tps


% Supplementary Figure XX
f=figure;
IsoCacnesLineages = TemporalDynamicsIndividual(AcacnesIso,IsolateArrays,MinAssigned,cutoff_real,"C. acnes lineages, Isolates");
sgtitle('isolates, C. acnes lineage-level')
%
saveas(f,'ManuscriptFigures/TemporalDynamicsIndividual_IsoCacnesLineages.svg')
%
f=figure;
IsoSepiLineages = TemporalDynamicsIndividual(AsepiIso,IsolateArrays,MinAssigned,cutoff_real,"S. epidermidis lineages, Isolates");
sgtitle('isolates, S. epidermidis lineage-level')
%
saveas(f,'ManuscriptFigures/TemporalDynamicsIndividual_IsoSepiLineages.svg')
%;
f=figure;
MGCacnesLineages = TemporalDynamicsIndividual(MsubjectTime.CombinedCacnesLineages,MsubjectTime,MinAssigned,cutoff_real,"C. acnes lins., Metagenomics, combined");
sgtitle('metagenomics, C. acnes lineage-level')
%
saveas(f,'ManuscriptFigures/TemporalDynamicsIndividual_MGCacnesLineages.svg')
%
f=figure;
MGSepiLineages = TemporalDynamicsIndividual(MsubjectTime.CombinedSepiLineages,MsubjectTime,MinAssigned,cutoff_real,"S. epidermidis lins., Metagenomics, combined");
sgtitle('metagenomics, S. epidermidis lineage-level')
%
saveas(f,'ManuscriptFigures/TemporalDynamicsIndividual_MGSepiLineages.svg')
%
f=figure;
MGCacnesPhylo = TemporalDynamicsIndividual(MsubjectTime.CombinedCacnesPhylotypes,MsubjectTime,MinAssigned,cutoff_real,"C. acnes phylotypes, Metagenomics,loose");
sgtitle('metagenomics, C. acnes phylotype-level')
%
saveas(f,'ManuscriptFigures/TemporalDynamicsIndividual_MGCacnesPhylo.svg')
%
f=figure;
MGSepiSubphylo = TemporalDynamicsIndividual(MsubjectTime.CombinedSepiSubphylo,MsubjectTime,MinAssigned,cutoff_real,"S. epidermidis subphylotypes, Metagenomics,combined");
sgtitle('metagenomics, S. epidermidis subphylotype-level')
%
saveas(f,'ManuscriptFigures/TemporalDynamicsIndividual_MGSepiSubphylo.svg')
%
f=figure
MGSepiPhylo = TemporalDynamicsIndividual(MsubjectTime.CombinedSepiPhylo,MsubjectTime,MinAssigned,cutoff_real,"S. epidermidis phylotypes, Metagenomics, combined");
sgtitle('metagenomics, S. epidermidis phylotype-level')
%
saveas(f,'ManuscriptFigures/TemporalDynamicsIndividual_MGSepiPhylo.svg')


%% plot the absolute number of S. epidermidis clades per group


% Figure 4G
% Supplementary Figure XX
cutoff_assigned=.7;
cutoff_real=.01;

f=figure;
[~,Nmean_iso_lin,Tbl_iso_lin] = n_clades_by_group(IsolateArrays,AsepiIso,cutoff_assigned,cutoff_real,"S. epi lineages, Isolates");
 saveas(f,'ManuscriptFigures/Nclades_Sepi_lineages_isolates.svg')

f=figure;
[~,Nmean_mg_lin,Tbl_mg_lin] = n_clades_by_group(MsubjectTime,MsubjectTime.CombinedSepiLineages,cutoff_assigned,cutoff_real,"S. epi lineages, Metagenomics");
saveas(f,'ManuscriptFigures/Nclades_Sepi_lineages_metagenomics.svg')

f=figure; 
p = n_clades_by_group(MsubjectTime,MsubjectTime.CombinedSepiSubphylo,cutoff_assigned,cutoff_real,"S. epi subphylotypes, Metagenomics");
saveas(f,'ManuscriptFigures/Nclades_Sepi_subphylotypes_metagenomics.svg')


%% plot the absolute number of C. acnes clades per group


% Figure 5F
% Supplementary Figure XX
cutoff_assigned=.7;
cutoff_real=.01;

f=figure
p = n_clades_by_group(IsolateArrays,AcacnesIso,cutoff_assigned,cutoff_real,"C. acnes lineages, Isolates")
saveas(f,'ManuscriptFigures/Nclades_Cacnes_lineages_isolates.svg')

%

f=figure
p = n_clades_by_group(MsubjectTime,MsubjectTime.CombinedCacnesLineages,cutoff_assigned,cutoff_real,"C. acnes lineages, Metagenomics")
saveas(f,'ManuscriptFigures/Nclades_Cacnes_lineages_metagenomics.svg')

%

f=figure
p = n_clades_by_group(MsubjectTime,MsubjectTime.CombinedCacnesPhylotypes,cutoff_assigned,cutoff_real,"C. acnes subphylotypes, Metagenomics")
saveas(f,'ManuscriptFigures/Nclades_Cacnes_phylotypes_metagenomics.svg')


%% save important data structures


save('data/IT.mat','IT')
save('data/LineageData.mat','LineageData')
save data/MetagenomicsSampleTables.mat Mtubes MsubjectTime Msubject


%% ST1: make supplementary table 1, to quickly give basic info about subjects


mkdir data/SupplementaryTables
ST1 = MsubjectTime;
ST1=ST1(:,[1 2 3 4]);
writetable(ST1,'data/SupplementaryTables/age_sex_each_subject.csv')


%% make version of metagenomics data able to be written to .csv


MtubesTable = parse_to_csv_version(Mtubes);
MSubjectTimeTable = parse_to_csv_version(MsubjectTime);
MSubjectTable = parse_to_csv_version(Msubject);


%% fix some fields


MSubjectTimeTable.location = arrayfun(@(x) strjoin(x{:},' '), MSubjectTimeTable.location);
MSubjectTable.location = arrayfun(@(x) strjoin(x{:},' '), MSubjectTable.location);
MSubjectTable.TP = arrayfun(@(x) char(strjoin(string(x{:}),' ')), MSubjectTable.TP);
MSubjectTable.TP =string(MSubjectTable.TP );

writetable(MtubesTable,'data/SupplementaryTables/metagenomics_sample_data_by_individual_tubes.csv')
writetable(MSubjectTimeTable,'data/SupplementaryTables/metagenomics_sample_data_by_subject_timepoint.csv')
writetable(MSubjectTable,'data/SupplementaryTables/metagenomics_sample_data_by_subject.csv')


%% Reproduces numbers stated in the results section


NreadsByTubeSpecies=vertcat(Mtubes.BrackenReadsAssignedSpecies{:});
NreadsByTubeSpecies=NreadsByTubeSpecies(:,~(Mtubes.NamesSpecies(1,:)=="Homo sapiens"));
NreadsByTubeSpecies=sum(NreadsByTubeSpecies,2);
MeanNreadsByTubeSpecies=round(mean(NreadsByTubeSpecies),2,'significant');

% total numbers of isolates
NumberOfSepiIsolates = sum(IT.SpeciesString=="sepi");
NumberOfCacnesIsolates = sum(IT.SpeciesString=="cacnes");

% ages of facial cutotype 1 and 2 subjects
MedianFC1AgeSubject=median(Msubject.Age(Msubject.subject_cutotype==1));
MedianFC2AgeSubject=median(Msubject.Age(Msubject.subject_cutotype==2));

% median age at sampling for FC1 and FC2 kits
MedianFC1AgeSubjectTime=median(MsubjectTime.Age(MsubjectTime.umap_clusters_subjecttime_bracken_species==1&~contains(MsubjectTime.SID,"P")));
MedianFC2AgeSubjectTime=median(MsubjectTime.Age(MsubjectTime.umap_clusters_subjecttime_bracken_species==2&~contains(MsubjectTime.SID,"P")));

% number of S. epi or C. acnes isolates per subject/timepoint
TSepi=tabulate(IT.SubjectTime(IT.SpeciesString=="sepi"));
TCacnes=tabulate(IT.SubjectTime(IT.SpeciesString=="cacnes"));

% most isolates collected per species
MaxSepiPerSampling=max(vertcat(TSepi{:,2}));
MaxCacnesPerSampling=max(vertcat(TCacnes{:,2}));

% N lineages per species
NCacnesLineages=numel(unique(IT.ClusterString(IT.SpeciesString=="cacnes")));
NSepiLineages=numel(unique(IT.ClusterString(IT.SpeciesString=="sepi")));

% younger kids have fewer S. epi cultures
IsSepi=IT.SpeciesString=="sepi";

FN = SID2FamilyNumbers(Msubject.SID);
Nsepiisolates=arrayfun(@(x) sum(IsSepi&IT.Subject==x), Msubject.SID);

[h,p,k]=kstest2(Nsepiisolates(FN'<9&Msubject.subject_cutotype==2),Nsepiisolates(FN'<9&Msubject.subject_cutotype==1))


%% Histograms of pairwise tubes to total concatenated kits


% Supplemental Figure XX
% tube_site_specificity(Mtubes)
[SepiPhyloTubes] = plot_clade_site_specificity(Mtubes,Mtubes.SepiPhylotypeAbundance,'S. epidermidis phylotypes');
[CacnesPhyloTubes] = plot_clade_site_specificity(Mtubes,Mtubes.CacnesPhylotypeAbundance,'C. acnes phylotypes');
set(0, 'DefaultFigureRenderer', 'painters');
saveas(SepiPhyloTubes,'ManuscriptFigures/Supplemental_sepi_site_specificity.svg','svg')
saveas(CacnesPhyloTubes,'ManuscriptFigures/Supplemental_cacnes_site_specificity.svg','svg')


%% 11PA is an adult subject with unusual composition


% Supplementary Figure XX
p=bracken_stackedbar_maker(Mtubes(Mtubes.SID=="11PA",:),.01)
saveas(p,'ManuscriptFigures/Supplemental_unusual_abundance.svg','svg')


%% Plots cutotype cluster of each subject's time point samples


% Supplemental figure XX
MsubjectTime.UMAPClustersSubjectTime=double(MsubjectTime.umap_clusters_subjecttime_bracken_species)
p=plot_cutotypes_per_tp(MsubjectTime,ManuscriptColors)
saveas(p,'ManuscriptFigures/Supplemental_IndividualTimepointCutotypes.svg','svg')


%% compares the number of lineages found in metagenomics to isolates
% and also the abundance of them


% Supplementary Figure XX
% Figure 3B
cutoff_isolates=25
cutoff_assigned=.7
cutoff_real=0
compare_isolates_metagenomics(IT,MsubjectTime,cutoff_isolates,cutoff_assigned,cutoff_real)


%% plots all data for family 1


plot_all_lineages_family(MsubjectTime)


%% stacked histogram bars of max within lineage dMRCAs


% Figure 3A
f=plot_within_cluster_distance(LineageData,ManuscriptColors)
saveas(f,'ManuscriptFigures/within_lineage_distances.svg')


%% Plots the bray-cutyis dissimilarity of related and related individuals


% Figure 3F
f=plot_related_unrelated_diversity(MsubjectTime,.7,.01)
saveas(f,'ManuscriptFigures/related_unrelated_pairs_jaccard.svg','svg')


%% Polarized Tajima's D


% Supplementary Figure XX
% Parse LineageDaya to get info about dMRCAs
LineageDMRCAs=get_lineage_dmrcas(LineageData,Msubject);


%% Make csv exportable version of lineage data


LineageDMRCAsForSupplement = LineageData2supplement(LineageDMRCAs);
writetable(LineageDMRCAsForSupplement, 'data/SupplementaryTables/LineageDMRCAsForSupplement.csv')


%% compare 2*pairwise distance versus dMRCA aka "branchiness" for each lineage


% Supplemental figure XX
LineageData = dmrca_vs_d_pairwise(LineageDMRCAs);


%% Compare directionality of transmission using lineage dMRCAs


% Supplementary Figure XX
% Figure 3 Supplement
L = LineageDMRCAs(LineageDMRCAs.Nisolates>=3&LineageDMRCAs.Species=="cacnes"&LineageDMRCAs.Unshared==0,:);

% FamilyNumbers = get_family_numbers(L.SID);
% NFamiliesInLineage=arrayfun(@(x) numel(unique(FamilyNumbers(L.LineageNumber(x)==L.LineageNumber))), 1:size(L,1));
% L2=L(NFamiliesInLineage>1,:);
total_n_lineages=numel(unique(LineageData.cladenumber(LineageData.SpeciesName=="cacnes")));
total_shared=numel(unique(LineageDMRCAs.LineageNumber(LineageDMRCAs.Species=="cacnes"&LineageDMRCAs.Unshared==0)));
CacnesProportionSharedLineages=total_shared/total_n_lineages;

[p, f2,f3] = shared_lineage_directionality(L,total_n_lineages,total_shared);
saveas(p,'ManuscriptFigures/cacnes_dDMRCA.svg')
saveas(f2,'ManuscriptFigures/NclearUnclearCacnes.svg')
saveas(f3,'ManuscriptFigures/cacnes_dDMRCA_clearonly.svg')


% As above, but for S. epidermidis


% Supplementary Figure XX
L = LineageDMRCAs(LineageDMRCAs.Nisolates>=3&LineageDMRCAs.Species=="sepi"&LineageDMRCAs.Unshared==0,:);

total_n_lineages=numel(unique(LineageData.cladenumber(LineageData.SpeciesName=="sepi")));
total_shared=numel(unique(LineageDMRCAs.LineageNumber(LineageDMRCAs.Species=="sepi"&LineageDMRCAs.Unshared==0)));
[p, f2,f3] = shared_lineage_directionality(L,total_n_lineages,total_shared);
saveas(p,'ManuscriptFigures/sepi_dDMRCA.svg')
saveas(f2,'ManuscriptFigures/NclearUnclearSepi.svg')
saveas(f3,'ManuscriptFigures/sepi_dDMRCA_clearonly.svg')
SepiProportionSharedLineages=total_shared/total_n_lineages


%% Simulations showing that lineages are not over-dispersed on individuals


% Supplementary Figure XX
% Get pair-wise distance matrix
% GoodDMs.mat is the distance matrices actually used, the other oens are
% saved for reproducability only
load GoodDMs.mat
CacnesLineages=load('data/cacnes_clusters.mat');
SepiLineages=load('data/sepi_clusters.mat');
CacnesLineageNumbers=Msubject.CacnesLineageNumbers(1,:); % Ns of lineages you actually want to measure
CacnesClusterDM=intercluster_dm(CacnesDM,CacnesLineages.clusters,CacnesLineageNumbers);
SepiLineageNumbers=Msubject.SepiLineageNumbers(1,:); % Ns of lineages you actually want to measure
SepiClusterDM=intercluster_dm(SepiDM,SepiLineages.clusters,SepiLineageNumbers);

% parameters for simulations which are the same
CutoffAssigned=.7;
CutoffReal=.01;
T=100000;
replacement=false; % this is incorrect, need to fix
SID=MsubjectTime.SID

% C. acnes simulations
A=MsubjectTime.CombinedCacnesLineages;
DM=CacnesClusterDM;
[p,CacnesGenomeDistanceSimulations]=simulate_lineage_differences_subject(SID,A,CutoffAssigned,CutoffReal,DM,T,replacement)
p.Position=[413         537        1349         404];
saveas(p,'ManuscriptFigures/Supplemental_Cacnes_distance_simulations.pdf')

% S. epi simulations
A=MsubjectTime.CombinedSepiLineages;
DM=SepiClusterDM;
[p,SepiGenomeDistanceSimulations]=simulate_lineage_differences_subject(SID,A,CutoffAssigned,CutoffReal,DM,T,replacement)
p.Position=[413         537        1349         404];
saveas(p,'ManuscriptFigures/Supplemental_Sepi_distance_simulations.pdf')


% As above, but for gene content instead of between-cluster distance


% DMs of flexible gene content
% only genes below cutoff_core frequency will be included
% set to 2 to turn off
cutoff_core=2;
DM_cacnes_genecontent=get_dm_flexible_genecontent(Msubject.CacnesLineageNumbers(1,:),"cacnes",cutoff_core);
DM_sepi_genecontent=get_dm_flexible_genecontent(Msubject.SepiLineageNumbers(1,:),"sepi",cutoff_core);

% C. acnes simulations
A=MsubjectTime.CombinedCacnesLineages;
[p,CacnesGenomeContentSimulations]=simulate_lineage_differences_subject(MsubjectTime.SID,A,CutoffAssigned,CutoffReal,DM_cacnes_genecontent,T,replacement)
p.Position=[413         537        1349         404];
%
saveas(p,'ManuscriptFigures/Supplemental_Cacnes_flexible_genecontent_simulations.pdf')
% .renamecats
% S. epi simulations
A=MsubjectTime.CombinedSepiLineages;
DM=SepiClusterDM;
[p,SepiGenomeContentSimulations]=simulate_lineage_differences_subject(SID,A,CutoffAssigned,CutoffReal,DM_sepi_genecontent,T,replacement);
p.Position=[413         537        1349         404];
saveas(p,'ManuscriptFigures/Supplemental_Sepi_flexible_genecontent_simulations.pdf')

%% Save data


save('data/coexisting_lineage_dispersion_simulations.mat','CacnesGenomeContentSimulations','SepiGenomeContentSimulations','SepiGenomeDistanceSimulations','CacnesGenomeDistanceSimulations','-v7.3')


%% Hard-coded BH correction. integrate into code;


pvs=[.10998 .35094 .04658 .0308 .17268 .02038 .73482 .56446 .87532 .00972 .00768 .01452];
psort = sort(pvs)

crit = ((1:numel(pvs))/numel(pvs))*.05
psort<=crit


%% Pull out relavent simulations and plot them for main text


% Figure 3C
% plot cacnes and sepi simulations together
bw=.005;    
f=figure
histogram(CacnesGenomeContentSimulations.SimMin,'EdgeColor','black','FaceColor','white','FaceAlpha',.5,'BinWidth',bw)
hold on
histogram(SepiGenomeContentSimulations.SimMin,'EdgeColor','black','FaceColor','black','FaceAlpha',.5,'BinWidth',bw)
hold on
bar(CacnesGenomeContentSimulations.MinReal,18000,'BarWidth',bw/2,'FaceColor','red','EdgeColor','white')
bar(SepiGenomeContentSimulations.MinReal,18000,'BarWidth',bw/2,'FaceColor','red','EdgeColor','black')

xlim([0 .25])
pbaspect([1 1 1])
xlabel('min genome content distance between coexisting lineages')
ylabel('number of simulations (T=100000)')
l=legend;
l.String={'Cacnes Simulations' 'Sepi Simulations' 'Cacnes Observed' 'Sepi Observed'};

saveas(f,'ManuscriptFigures/MinGeneContentDifferenceLineages.svg')


%% Compare pairwise SNP distance to jaccard genome distance as evidence for gain loss


% Supplemental Figure XX
load GoodDMs.mat
CacnesLineages=load('data/cacnes_clusters.mat');
SepiLineages=load('data/sepi_clusters.mat');
load data/MetagenomicsSampleTables.mat Msubject
CacnesLineageNumbers=Msubject.CacnesLineageNumbers(1,:); % Ns of lineages you actually want to measure
SepiLineageNumbers=Msubject.SepiLineageNumbers(1,:); % Ns of lineages you actually want to measure
CacnesClusterDM=intercluster_dm(CacnesDM,CacnesLineages.clusters,CacnesLineageNumbers);
SepiClusterDM=intercluster_dm(SepiDM,SepiLineages.clusters,SepiLineageNumbers);
CacnesBool = tril(ones(size(CacnesClusterDM)),-1)==1;
SepiBool = tril(ones(size(SepiClusterDM)),-1)==1;

cutoff_core=2;
DM_cacnes_genecontent=get_dm_flexible_genecontent(Msubject.CacnesLineageNumbers(1,:),"cacnes",cutoff_core);
DM_sepi_genecontent=get_dm_flexible_genecontent(Msubject.SepiLineageNumbers(1,:),"sepi",cutoff_core);

%
f=figure

scatter(CacnesClusterDM(CacnesBool),DM_cacnes_genecontent(CacnesBool),'filled','MarkerFaceColor',[.85 .85 .85])
hold on
scatter(SepiClusterDM(SepiBool),DM_sepi_genecontent(SepiBool),'filled','MarkerFaceColor','black')
xlabel('pairwise SNP distance between lineages'); ylabel('Jaccard distance (genes)');
l=legend;
l.String={'C. acnes','S. epi'}
saveas(f,'ManuscriptFigures/SupplementalCoreGenomeVersusSNPDistance.svg')


%% show that pairs of lineages from same family are not common 

% supplementary figure XX
FamiliesCacnes = arrayfun(@(x) { unique(IT.Family(IT.SpeciesString=="cacnes"&IT.ClusterString==x)) }, CacnesLineageNumbers);
FamiliesSepi = arrayfun(@(x) { unique(IT.Family(IT.SpeciesString=="sepi"&IT.ClusterString==x)) }, SepiLineageNumbers);

AnySameSubjectBoolCacnes = zeros(87);
AnySameSubjectBoolSepi = zeros(76);

for i = 1:87
    for j = 1:87
        AnySameSubjectBoolCacnes(i,j)=numel(intersect(FamiliesCacnes{i},FamiliesCacnes{j}))>0;
    end
end
%

for i = 1:76
    for j = 1:76
        AnySameSubjectBoolSepi(i,j)=numel(intersect(FamiliesSepi{i},FamiliesSepi{j}))>0;
    end
end
%


CacnesClusterDM=intercluster_dm_pairs(CacnesDM,CacnesLineages.clusters,CacnesLineageNumbers);
SepiClusterDM=intercluster_dm_pairs(SepiDM,SepiLineages.clusters,SepiLineageNumbers);
% closest instances
% S. epidermidis lineages 24 and 71
% S. epidermidis lineages 64 and 93
% C. acnes 125 and 70å
%
f=figure;
subplot(4,1,1)
y = CacnesClusterDM;
b = AnySameSubjectBoolCacnes==1;
bool = tril(ones(size(b)),-1)==1;
Y = y(bool);
is_same = b(bool);
[Ysorted,idx]=sort(Y,'ascend');
is_same_sorted = is_same(idx);
%
x = 1:numel(Ysorted);
bar(x(is_same_sorted),Ysorted(is_same_sorted),'FaceColor','red','EdgeColor','none','BarWidth',1)
hold on
bar(x(~is_same_sorted),Ysorted(~is_same_sorted),'FaceColor','black','EdgeColor','none','BarWidth',1)
xlim([0 100])
xlabel('rank (ascending order)')
ylabel('pairwise inter-lineage distance')
l=legend;
l.String=[{'same family'} {'different family'}];
title('C. acnes inter-cluster distances')

subplot(4,1,2)
bar(x(is_same_sorted),Ysorted(is_same_sorted),'FaceColor','red','EdgeColor','none','BarWidth',1)
hold on
bar(x(~is_same_sorted),Ysorted(~is_same_sorted),'FaceColor','black','EdgeColor','none','BarWidth',1)
xlabel('rank (ascending order)')
ylabel('pairwise inter-lineage distance')

%
l=legend;
l.String=[{'same family'} {'different family'}];
%;
subplot(4,1,3)
y = SepiClusterDM;
b = AnySameSubjectBoolSepi==1;
bool = tril(ones(size(b)),-1)==1;
Y = y(bool);
is_same = b(bool);
[Ysorted,idx]=sort(Y,'ascend');
is_same_sorted = is_same(idx);
%
x = 1:numel(Ysorted);
bar(x(is_same_sorted),Ysorted(is_same_sorted),'FaceColor','red','EdgeColor','none','BarWidth',1)
hold on
bar(x(~is_same_sorted),Ysorted(~is_same_sorted),'FaceColor','black','EdgeColor','none','BarWidth',1)
xlim([0 100])
xlabel('rank (ascending order)')
ylabel('pairwise inter-lineage distance')
l=legend;
l.String=[{'same family'} {'different family'}];

title('S. epidermidis inter-cluster distances')
subplot(4,1,4)
bar(x(is_same_sorted),Ysorted(is_same_sorted),'FaceColor','red','EdgeColor','none','BarWidth',1)
hold on
bar(x(~is_same_sorted),Ysorted(~is_same_sorted),'FaceColor','black','EdgeColor','none','BarWidth',1)
xlabel('rank (ascending order)')
ylabel('pairwise inter-lineage distance')

%
l=legend;
l.String=[{'same family'} {'different family'}];


%% find the minimum number of transmisssiosn needed for each lineage, assiming a single source
% C. acnes figure, to explain why the phylogenies are so weird


%Figure 3E
LineageDataCacnes=LineageData(LineageData.SpeciesName=="cacnes",:);
LineageDataSepi=LineageData(LineageData.SpeciesName=="sepi",:);

f=figure;
subplot(3,2,1)
[Cacnesnumtransmissions, Cacnesnumisolates,CacnesTransmissions,CacnesNtotal_genotype_lineage,indices_has_transmissions_cacnes]=get_all_transmission_counts_pairwise(LineageDataCacnes,5,5);
ylim([0 6])
% parse
NisolatesSource = vertcat(CacnesTransmissions.NisolatesSource{:});
NTotalTransmissions = CacnesTransmissions.TotalTransmissions;
NisolatesRecipient = vertcat(CacnesTransmissions.NisolatesRecipient{:});
NTransmissionsRecipient = vertcat(CacnesTransmissions.Ntransmissions{:});
subplot(3,2,3)
scatter(NisolatesSource,NTotalTransmissions,'filled','MarkerFaceAlpha',.25,'MarkerEdgeColor','black')
hold on
ft1 = fit(NisolatesSource,NTotalTransmissions,'poly1');
[R,pv]=corr(NisolatesSource,NTotalTransmissions);
eq = ['y=' char(string(round(ft1.p1,2,'significant'))) 'x+' char(string(round(ft1.p2,2,'significant')))];
plot(ft1)
l=legend;
l.String={eq};
text(100,9,['R^2=' char(string(round(R^2,2,'significant')))])
text(100,7,['P=' char(string(round(pv,2,'significant')))])
xlabel('numisolates on source')
ylabel('Total N genotypes transmitted')
xlim([0 200])
ylim([0 12])
subplot(3,2,5)
scatter(NisolatesRecipient,NTransmissionsRecipient,'filled','MarkerFaceAlpha',.25,'MarkerEdgeColor','black')
hold on
ft1 = fit(NisolatesRecipient,NTransmissionsRecipient,'poly1');
[R,pv]=corr(NisolatesRecipient,NTransmissionsRecipient);
eq = ['y=' char(string(round(ft1.p1,2,'significant'))) 'x+' char(string(round(ft1.p2,2,'significant')))];
plot(ft1)
l=legend;
l.String={eq};
text(100,9,['R^2=' char(string(round(R^2,2,'significant')))])
text(100,7,['P=' char(string(round(pv,2,'significant')))])
xlabel('numisolates on recipient')
ylabel('N genotypes transmitted to recipient')
xlim([0 200])
ylim([0 12])
subplot(3,2,2)
[Sepinumtransmissions, Sepinumisolates,SepiTransmissions,SepiNtotal_genotype_lineage,indices_has_transmissions_sepi]=get_all_transmission_counts_pairwise(LineageDataSepi,5,5);

% parse
NisolatesSource = vertcat(SepiTransmissions.NisolatesSource{:});
NTotalTransmissions = SepiTransmissions.TotalTransmissions;
NisolatesRecipient = vertcat(SepiTransmissions.NisolatesRecipient{:});
NTransmissionsRecipient = vertcat(SepiTransmissions.Ntransmissions{:});
subplot(3,2,4)
scatter(NisolatesSource,NTotalTransmissions,'filled','MarkerFaceAlpha',.25,'MarkerEdgeColor','black')
hold on
ft1 = fit(NisolatesSource,NTotalTransmissions,'poly1');
[R,pv]=corr(NisolatesSource,NTotalTransmissions);
eq = ['y=' char(string(round(ft1.p1,2,'significant'))) 'x+' char(string(round(ft1.p2,2,'significant')))];
plot(ft1)
l=legend;
l.String={eq};
text(100,9,['R^2=' char(string(round(R^2,2,'significant')))])
text(100,7,['P=' char(string(round(pv,2,'significant')))])
xlabel('numisolates on source')
ylabel('Total N genotypes transmitted')
xlim([0 200])
ylim([0 12])
subplot(3,2,6)
scatter(NisolatesRecipient,NTransmissionsRecipient,'filled','MarkerFaceAlpha',.25,'MarkerEdgeColor','black')
hold on
ft1 = fit(NisolatesRecipient,NTransmissionsRecipient,'poly1');
[R,pv]=corr(NisolatesRecipient,NTransmissionsRecipient);
eq = ['y=' char(string(round(ft1.p1,2,'significant'))) 'x+' char(string(round(ft1.p2,2,'significant')))];
plot(ft1)
l=legend;
l.String={eq};
text(100,9,['R^2=' char(string(round(R^2,2,'significant')))])
text(100,7,['P=' char(string(round(pv,2,'significant')))])
xlabel('numisolates on recipient')
ylabel('N genotypes transmitted to recipient')
xlim([0 200])
ylim([0 12])
saveas(f,'ManuscriptFigures/NumGenotypesTransmitted.svg')


%% Compared the number of transmitted genotypes to the lesser of the number of isolartes from the donor and recipient
% Supplemental to number of transmitted gentypes figure above


% Supplemental figure XX
f=figure;
subplot(2,1,1)

NisoSource = arrayfun(@(x) {repmat(CacnesTransmissions.NisolatesSource{x},numel(CacnesTransmissions.NisolatesRecipient{x}),1)}, 1:size(CacnesTransmissions,1));
NisoSource=vertcat(NisoSource{:});
NisoRecip = vertcat(CacnesTransmissions.NisolatesRecipient{:});

Both = [NisoSource NisoRecip];
MinBoth = min(Both,[],2);
Ntrans =vertcat(CacnesTransmissions.Ntransmissions{:});
X=MinBoth;Y=Ntrans;
scatter(X,Y,'filled','MarkerFaceAlpha',.25,'MarkerEdgeColor','black')
hold on
ft1 = fit(X,Y,'poly1');
[R,pv]=corr(X,Y);
eq = ['y=' char(string(round(ft1.p1,2,'significant'))) 'x+' char(string(round(ft1.p2,2,'significant')))];
plot(ft1)
l=legend;
l.String={eq};
text(80,9,['R^2=' char(string(round(R^2,2,'significant')))])
text(80,7,['P=' char(string(round(pv,2,'significant')))])
xlabel('min numisolates between source and recipient')
ylabel('N genotypes transmitted')
xlim([0 100])
ylim([0 12])
title('C. acnes')
%
subplot(2,1,2)

NisoSource = arrayfun(@(x) {repmat(SepiTransmissions.NisolatesSource{x},numel(SepiTransmissions.NisolatesRecipient{x}),1)}, 1:size(SepiTransmissions,1));
NisoSource=vertcat(NisoSource{:});
NisoRecip = vertcat(SepiTransmissions.NisolatesRecipient{:});

Both = [NisoSource NisoRecip];
MinBoth = min(Both,[],2);
Ntrans =vertcat(SepiTransmissions.Ntransmissions{:});
X=MinBoth;Y=Ntrans;
scatter(X,Y,'filled','MarkerFaceAlpha',.25,'MarkerEdgeColor','black')
hold on
ft1 = fit(X,Y,'poly1');
[R,pv]=corr(X,Y);
eq = ['y=' char(string(round(ft1.p1,2,'significant'))) 'x+' char(string(round(ft1.p2,2,'significant')))];
plot(ft1)
l=legend;
l.String={eq};
text(80,9,['R^2=' char(string(round(R^2,2,'significant')))])
text(80,7,['P=' char(string(round(pv,2,'significant')))])
xlabel('min numisolates between source and recipient')
ylabel('N genotypes transmitted')
xlim([0 100])
ylim([0 12])
title('S. epidermidis')
saveas(f,'ManuscriptFigures/NumGenotypesTransmitted2.svg')


%% add some of these numbers to lineagedata to make supplement version


cacnes_ntrans = nan(size(LineageDataCacnes,1),1);
sepi_ntrans = nan(size(LineageDataSepi,1),1);
cacnes_idx = arrayfun(@(x) find(x==LineageDataCacnes.cladenumber), CacnesTransmissions.LineageNumber);
sepi_idx = arrayfun(@(x) find(x==LineageDataSepi.cladenumber), SepiTransmissions.LineageNumber);
cacnes_ntrans(cacnes_idx)=CacnesTransmissions.TotalTransmissions;
sepi_ntrans(sepi_idx)=SepiTransmissions.TotalTransmissions;
TotalTransmissions = [cacnes_ntrans; sepi_ntrans];
LineageData.TotalGenotypesTransmittedAllSubjects=TotalTransmissions;
SIDs=arrayfun(@(x) strjoin(LineageDMRCAs.SID(LineageDMRCAs.Species==LineageData.SpeciesName(x)&LineageDMRCAs.LineageNumber==LineageData.cladenumber(x)),' '), 1:size(LineageData,1));
Nisolates=arrayfun(@(x) strjoin(string(LineageDMRCAs.Nisolates(LineageDMRCAs.Species==LineageData.SpeciesName(x)&LineageDMRCAs.LineageNumber==LineageData.cladenumber(x))),' '), 1:size(LineageData,1));
LineageData.Subjects_with_isolates=SIDs';
LineageData.isolates_per_subjects=Nisolates';

% writetable(LineageData,'data/SupplementaryTables/LineageData.csv')

MedianNumberGenotypesTransmittedSepi=median(Sepinumtransmissions);
MedianNumberGenotypesTransmittedCacnes=median(Cacnesnumtransmissions);

%

LineageDataSupplement = table;
LineageDataSupplement.AncAlleles= arrayfun(@(x) {LineageData.anc_nti{x}(LineageData.goodpos{x})}, 1:size(LineageData,1))';
LineageDataSupplement.Samplenames= LineageData.samplenames;
LineageDataSupplement.in_outgroup= LineageData.outgroup;
LineageDataSupplement.p= LineageData.p;
LineageDataSupplement.alleles= LineageData.calls_analysis;
LineageDataSupplement.goodpos = LineageData.goodpos;


%% write csv for each one, and then put them together in one doc


R = size(LineageDataSupplement,1)
NTs=["N" "A" "T" "C" "G"]
names="";
tbs_all = {};
for i = 1:R
    row = LineageDataSupplement(i,:);
    name = strjoin([LineageData.SpeciesName(i) "clade" string(LineageData.cladenumber(i))],'_');
    names(i)=name;
    newtable = table;
    % newtable.anscestral_alleles = row.AncAlleles{:};
    newtable.name = string(row.Samplenames{:})';
    newtable.is_outgroup_sample = row.in_outgroup{:}';
    nucleotide = row.alleles{:};
    nucleotide=NTs(nucleotide+1)';
    % nucleotide=arrayfun(@(x){nucleotide(:,x)'}, 1:size(nucleotide,2))
    % newtable.nucleotide = nucleotide';
    % nucleotide=vertcat(newtable.nucleotide{:});
    pos = row.p{:}(row.goodpos{:}'==1)';
    for j = 1:numel(pos)
        newtable.(strjoin(["nt_position_" string(pos(j))],''))=nucleotide(:,j);
    end
    newtable.name(end+1)="ANSCESTRAL_ALLELE";
    anc_alleles = row.AncAlleles{:}';
    anc_alleles=NTs(anc_alleles);
    try
    newtable(end,3:end)=cellstr(anc_alleles);
    catch
    end
    writetable(newtable,[char(name) '.csv'])
    tbs_all{i}=newtable;
end

for i =1:numel(names)
    writematrix(names(i),'clade_all_muts_supplement.csv','WriteMode','append')
    writetable(tbs_all{i},'clade_all_muts_supplement.csv','WriteMode','append','WriteVariableNames',true)
end


LineageDataByLineage = LineageData;
LineageDataByLineage = removevars(LineageDataByLineage, ["anc_nti","goodpos","outgroup","calls_analysis","samplenames","p","fraction_ambiguous","tree_snps"]);
writetable(LineageDataByLineage,'data/SupplementaryTables/lineage_data.csv')

% p value for figure 3E
[h,p,k]=kstest2(vertcat(CacnesTransmissions.Ntransmissions{:}),vertcat(SepiTransmissions.Ntransmissions{:}))


%% Find genes which are mutated more times than expected by chance 


% Supplementary Figure XX
load data/annotations_all.mat

% parallel mutation analysis, C acnes
MutationSpectrumCacnes=main_muts(cacnes_annotations_all);
 MutationSpectrumSepi=main_muts(sepi_annotations_all);
save('data/MutationSpectrum.mat','MutationSpectrumCacnes','MutationSpectrumSepi')

% % mutations by lineage.
% need to fix to make it more clear what it's doing
% hits a bug when running S. epi now for some reaosn, need to fix
cacnes_annotations_all_mutgenes = evo_parallel_main_wrapper(cacnes_annotations_all,MutationSpectrumCacnes,'cacnes');
sepi_annotations_all_mutgenes = evo_parallel_main_wrapper(sepi_annotations_all,MutationSpectrumSepi,'sepi');
save('data/annotations_all_mutgenes.mat','sepi_annotations_all_mutgenes','cacnes_annotations_all_mutgenes')


%look at homologues with more strict cutoff for CDHIT
% S. epi figure, to show that we don't find any fitness
% Should re-do this analysis with ROARY? maybe not worth it to have to add
% methods section 


% We previously used CDHIT:
%[CDHITDataCladeAssemblies] = parse_cdhit_clusters(.93);
%  but it turns out that Roary is better, 
% so this script supplants it
% the script parevo_homologues has been accordingly modi
[RoaryDataCacnes, RoaryDataSepi]= parse_roary_clusters;

writetable(RoaryDataCacnes,'data/SupplementaryTables/ST9_RoaryDataCacnes.csv')
writetable(RoaryDataSepi,'data/SupplementaryTables/ST10_RoaryDataSepi.csv')

% Figure 4 (S. epi evolution)
[SepiAnnotationsHomologues,SepiAllProteinInfo]=parevo_homologues(sepi_annotations_all,MutationSpectrumSepi,RoaryDataSepi,'sepi');
[CacnesAnnotationsHomologues,CacnesAllProteinInfo]=parevo_homologues(cacnes_annotations_all,MutationSpectrumCacnes,RoaryDataCacnes,'cacnes');
save('data/AnnotationsHomologues.mat','SepiAllProteinInfo','CacnesAllProteinInfo','SepiAnnotationsHomologues','CacnesAnnotationsHomologues')

% Plot parallel evolution 

load data/AnnotationsHomologues.mat
load data/MutationSpectrum.mat MutationSpectrumCacnes MutationSpectrumSepi
% dNdS for most hit genes as well as dNdS by B/H FDR
[s1,s2,s3]=parevo_homologues_plot(SepiAnnotationsHomologues,MutationSpectrumSepi.prob_nonsyn);
[c1,c2,c3]=parevo_homologues_plot(CacnesAnnotationsHomologues,MutationSpectrumCacnes.prob_nonsyn);
saveas(c3,'ManuscriptFigures/Cacnes_multiple_mutated_genes_density.svg')
saveas(s3,'ManuscriptFigures/Sepi_multiple_mutated_genes_density.svg')


%% write annotations to supplementary tables to upload


SepiAllProteinInfo=struct2table(SepiAllProteinInfo);
CacnesAllProteinInfo=struct2table(CacnesAllProteinInfo);
SepiAnnotationsHomologues=struct2table(SepiAnnotationsHomologues);
CacnesAnnotationsHomologues=struct2table(CacnesAnnotationsHomologues);

SepiAnnotationsHomologues.annotations_indices = arrayfun(@(x) strjoin(string(x{:}),' '), SepiAnnotationsHomologues.annotations_indices);
CacnesAnnotationsHomologues.annotations_indices = arrayfun(@(x) strjoin(string(x{:}),' '), CacnesAnnotationsHomologues.annotations_indices);

writetable(SepiAllProteinInfo,'data/SupplementaryTables/SepiAllProteinInfo.csv')
writetable(CacnesAllProteinInfo,'data/SupplementaryTables/CacnesAllProteinInfo.csv')
writetable(SepiAnnotationsHomologues,'data/SupplementaryTables/SepiAnnotationsHomologues.csv')
writetable(CacnesAnnotationsHomologues,'data/SupplementaryTables/CacnesAnnotationsHomologues.csv')


%% Get molecular clocks for all lineages


% Supplementary figure XX
% WARNING: need to fix script, commented out part that makes plots
[SubjectClusterPairs,tps,root_to_tip]=molecular_clock(LineageData,5);
 

%% Molecular clock for S. epidermidis


% Supplementary Figure XXnumber of
% for S. epi
[f1,f2,f3]=plot_molecularclocks_individual(SubjectClusterPairs,tps,root_to_tip,MsubjectTime);
saveas(f1,'ManuscriptFigures/CacnesMolecularClockSignificance.svg');
saveas(f2,'ManuscriptFigures/SepiMolecularClockSignificance.svg');
saveas(f3,'ManuscriptFigures/SepiMolecularClocksIndividual.svg');
% WARNING: molecular clock rate for S. epi is hardcoded becasuee i need to
% fix script
[SepiMolecularClockRate, p]= get_sepi_mol_clock(SubjectClusterPairs,tps,root_to_tip);
saveas(p,'ManuscriptFigures/SepiMolecularClockAllTogether.svg');


%% For both species, show that unshared lineages are not significantly older than shared ones


% Supplementary Figure XX
L = LineageDMRCAs(LineageDMRCAs.Nisolates>=5&LineageDMRCAs.Species=="cacnes",:);
f=figure;
L = LineageDMRCAs(LineageDMRCAs.Nisolates>=5&LineageDMRCAs.Species=="cacnes",:);
average_dMRCA = cellfun(@mean ,L.dMRCA_subject_isolates);
unshared = L.Unshared;
LUnshared=L(unshared,:);
LShared = L(~unshared,:);
swarmchart(unshared+1, average_dMRCA,'filled','CData',ManuscriptColors.CutotypeColors(L.Cutotype,:),'XJitterWidth',.5)
hold on
plot([.75 1.25],[median(average_dMRCA(unshared==0)) median(average_dMRCA(unshared==0))])
plot([1.75 2.25],[median(average_dMRCA(unshared==1)) median(average_dMRCA(unshared==1))])

xticks([1:2])
xticklabels(["Shared" "Unshared"])
ylabel('average dMRCA')
p=ranksum(average_dMRCA(unshared),average_dMRCA(~unshared));
text(1,30,['p=' char(string(p))])
saveas(f,'ManuscriptFigures/Cacnes_shared_vs_unshared_dMRCA.svg')
%
L = LineageDMRCAs(LineageDMRCAs.Nisolates>=5&LineageDMRCAs.Species=="sepi",:);
f=figure;
% WARNING: need to add switch which plots the points colored by
% shared/unshared insrtead of group, lines currently commented out
% C. acnes
% Figure 4(C. acnes)
clrsgroups=ManuscriptColors.CutotypeColors;
average_dMRCA = cellfun(@mean ,L.dMRCA_subject_isolates);
unshared = L.Unshared;
LUnshared=L(unshared,:);
LShared = L(~unshared,:);
swarmchart(unshared+1, average_dMRCA,'filled','CData',ManuscriptColors.CutotypeColors(L.Cutotype,:),'XJitterWidth',.5)
hold on
plot([.75 1.25],[median(average_dMRCA(unshared==0)) median(average_dMRCA(unshared==0))])
plot([1.75 2.25],[median(average_dMRCA(unshared==1)) median(average_dMRCA(unshared==1))])

xticks([1:2])
xticklabels(["Shared" "Unshared"])
ylabel('average dMRCA')
p=ranksum(average_dMRCA(unshared),average_dMRCA(~unshared));
text(1,30,['p=' char(string(p))])
saveas(f,'ManuscriptFigures/Sepi_shared_vs_unshared_dMRCA.svg')


%% For both species, compare dMRCAs to age


% Figure 5A
% Figure 5B
% Figure 5C
% Figure 5D
% Figure 5E
L = LineageDMRCAs(LineageDMRCAs.Nisolates>=5&LineageDMRCAs.Species=="cacnes",:);
[fMin,fMean,fMax,fAll,fStacked]=compare_lineage_dmrcas(L,0,"dMRCA_subject_isolates",clrsgroups,'C. acnes unshared lineage subject dMRCAs');
%
saveas(fMin,'ManuscriptFigures/Cacnes_minniso5_Min_dMRCA_subject_isolates.svg')
saveas(fMean,'ManuscriptFigures/Cacnes_minniso5_Mean_dMRCA_subject_isolates.svg')
saveas(fMax,'ManuscriptFigures/Cacnes_minniso5_Max_dMRCA_subject_isolates.svg')
saveas(fAll,'ManuscriptFigures/Cacnes_minniso5_All_dMRCA_subject_isolates.svg')
saveas(fStacked,'ManuscriptFigures/Cacnes_minniso5_AllStacked_dMRCA_subject_isolates.svg')


%% as above, for S. epidermidis


% Figure 4D
% Figure 4E
% Figure 4F
L = LineageDMRCAs(LineageDMRCAs.Nisolates>=5&LineageDMRCAs.Species=="sepi",:);
[fMin,fMean,fMax,fAll,fStacked]=compare_lineage_dmrcas(L,SepiMolecularClockRate,"dMRCA_subject_isolates",clrsgroups,'S. epidermidis unshared lineage subject dMRCAs');
saveas(fMin,'ManuscriptFigures/Sepi_minniso5_Min_tMRCA_subject_isolates.svg')
saveas(fMean,'ManuscriptFigures/Sepi_minniso5_Mean_tMRCA_subject_isolates.svg')
saveas(fMax,'ManuscriptFigures/Sepi_minniso5_Max_tMRCA_subject_isolates.svg')
saveas(fAll,'ManuscriptFigures/Sepi_minniso5_All_tMRCA_subject_isolates.svg')
saveas(fStacked,'ManuscriptFigures/Sepi_minniso5_AllStacked_tMRCA_subject_isolates.svg')


%% Compare relative S. epi./C. acnes abundance across groups


% Supplementary Figure XX
clrsgroups=ManuscriptColors.CutotypeColors;
% Figure 2 or 4/5 supplement

% add ratio of C. acnes/S. epi human reads to Msubject
Msubject=get_species_human_ratio(Msubject);

p=plot_sepi_cacnes_abundance(Msubject,clrsgroups)
saveas(p,'ManuscriptFigures/Supplemental_RelAbundance_Cacnes_Sepi_By_group.svg')


%% %% Plot the number of subjects in each lineage
% Not currently used
% Supplemental Figure XX
% make this a function
% Figure 3 (lineage sharing and uniqueness)


NsubjectsPerClade = arrayfun(@(x) {LineageData.samplenames{x}(~LineageData.outgroup{x})}, 1:167);
NsubjectsPerClade = arrayfun(@(x) {char(x{:})}, NsubjectsPerClade);
NsubjectsPerClade(cellfun(@isempty,NsubjectsPerClade))={'   '};
NsubjectsPerClade = arrayfun(@(x) {string(x{:}(:,1:3))}, NsubjectsPerClade);
NsubjectsPerClade = arrayfun(@(x) numel(unique(x{:}(x{:}~="   "))), NsubjectsPerClade);
figure
subplot(2,1,1)
histogram(NsubjectsPerClade(NsubjectsPerClade'~=0&LineageData.SpeciesName=="cacnes"),'FaceColor',[.85 .85 .85])
xlim([0 6])
ylim([0 60])
xticks([1:5])
title('C. acnes')
xlabel('Number of subjects per lineage')
ylabel('Number of lineages')
pbaspect([1 1 1])
subplot(2,1,2)
histogram(NsubjectsPerClade(NsubjectsPerClade'~=0&LineageData.SpeciesName=="sepi"),'FaceColor',[.85 .85 .85])
title('S. epidermidis')
xlim([0 6])
ylim([0 60])
xticks([1:5])
xlabel('Number of subjects per lineage')
ylabel('Number of lineages')
pbaspect([1 1 1])


%% proportion lineages more than one person


CacnesN = NsubjectsPerClade(NsubjectsPerClade'~=0&LineageData.SpeciesName=="cacnes");
SepiN = NsubjectsPerClade(NsubjectsPerClade'~=0&LineageData.SpeciesName=="sepi");

mean(CacnesN>1)
mean(SepiN>1)